/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'isVerified' : IDL.Bool,
  'industry' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'isPotentiallyFraudulent' : IDL.Bool,
  'reasons' : IDL.Vec(IDL.Text),
  'confidenceScore' : IDL.Nat,
  'companyInfo' : IDL.Opt(CompanyInfo),
  'verifiedEmailDomain' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'analyzeJobPosting' : IDL.Func([IDL.Nat], [AnalysisResult], ['query']),
  'submitJobPosting' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'isVerified' : IDL.Bool,
    'industry' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'isPotentiallyFraudulent' : IDL.Bool,
    'reasons' : IDL.Vec(IDL.Text),
    'confidenceScore' : IDL.Nat,
    'companyInfo' : IDL.Opt(CompanyInfo),
    'verifiedEmailDomain' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'analyzeJobPosting' : IDL.Func([IDL.Nat], [AnalysisResult], ['query']),
    'submitJobPosting' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };